apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  namespace: realfds
data:
  flink-conf.yaml: |+
    jobmanager.rpc.address: flink-jobmanager
    taskmanager.numberOfTaskSlots: 4
    parallelism.default: 2
    jobmanager.memory.process.size: 1600m
    taskmanager.memory.process.size: 1728m
    state.backend: rocksdb
    state.checkpoints.dir: file:///flink-checkpoints
    state.savepoints.dir: file:///flink-savepoints
    execution.checkpointing.interval: 60s
    execution.checkpointing.min-pause: 10s
  log4j-console.properties: |+
    rootLogger.level = INFO
    rootLogger.appenderRef.console.ref = ConsoleAppender
    appender.console.name = ConsoleAppender
    appender.console.type = CONSOLE
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
